spring.application.name=algusto
spring.profiles.active=dev
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173
spring.security.oauth2.client.registration.google.scope=openid,profile,email
